DROP DATABASE `wallet_logger`;
CREATE DATABASE `wallet_logger`;
GRANT ALL PRIVILEGES ON `wallet_logger`.* TO 'CHOOSE_YOUR_DB_USER'@'CHOOSE_YOUR_SOURCE_HOST' IDENTIFIED BY 'CHOOSE_YOUR_DB_PASSWORD';

USE `wallet_logger`;

DROP TABLE IF EXISTS `wallets`;
CREATE TABLE IF NOT EXISTS `wallets` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `accounts`;
CREATE TABLE IF NOT EXISTS `accounts` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`wallet_id` INT NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `transactions`;
CREATE TABLE IF NOT EXISTS `transactions` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`wallet_id` INT NOT NULL,
	`transaction_date` DATETIME NOT NULL,
	`description` TEXT NOT NULL,
	`amount` FLOAT(10,2) NOT NULL DEFAULT 0.00,
	`direction` ENUM('IN','OUT') NOT NULL,
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	`deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
);
